# Generated by Django 2.2.28 on 2023-02-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230209_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='url',
        ),
        migrations.AddField(
            model_name='blogs',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
