# Generated by Django 2.2.28 on 2023-02-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230218_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
